﻿export type PageKey = 
  | 'home' 
  | 'products' 
  | 'membership' 
  | 'custom-design' 
  | 'about' 
  | 'login' 
  | 'register' 
  | 'search' 
  | 'product-detail' 
  | 'cart' 
  | 'admin' 
  | 'checkout'
  | 'pay_success'
  | 'pay_fail'
